# Generated by Django 2.2.5 on 2020-08-17 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usersphone',
            fields=[
                ('uid', models.CharField(auto_created=True, max_length=225, primary_key=True, serialize=False)),
                ('phnumber1', models.IntegerField(blank=True, default=0, unique=True)),
                ('phnumber2', models.IntegerField(blank=True, null=True, unique=True)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
