# Generated by Django 2.2.5 on 2020-08-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200817_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userimage',
            field=models.ImageField(default='default.jpg', upload_to='media'),
        ),
    ]
