# Generated by Django 2.2.5 on 2020-08-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_userimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userimage',
        ),
        migrations.AddField(
            model_name='usersphone',
            name='userimage',
            field=models.ImageField(default='default.jpg', upload_to='media'),
        ),
    ]
