# Generated by Django 2.2.5 on 2020-08-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200820_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersphone',
            name='userimage',
            field=models.ImageField(default='default.jpg', upload_to='users'),
        ),
    ]
