# Generated by Django 2.2.5 on 2020-08-23 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_auto_20200820_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('walletid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Balanceamt', models.FloatField(default=0.0)),
                ('bank', models.IntegerField(choices=[(1, 'ANDHRA BANK'), (2, 'ALLAHABAD  BANK'), (3, 'AXIS BANK'), (4, 'BANK OF BARODA'), (5, 'BANK OF INDIA'), (6, 'BANK OF MAHARASHTRA'), (7, 'CENTRAL BANK OF INDIA'), (8, 'CANARA BANK'), (9, 'CATHOLIC SYRIAN BANK'), (10, 'CITI BANK'), (11, 'CORPORATION BANK'), (12, 'DENA BANK'), (13, 'DHANALAKSHMI BANK'), (14, 'FEDERAL BANK'), (15, 'HDFC BANK'), (16, 'ICICI BANK'), (17, 'INDIAN BANK'), (18, 'INDIAN OVERSEAS BANK'), (19, 'INDUSIND BANK'), (20, 'IDBI BANK'), (21, 'JAMMU AND KASHMIR BANK'), (22, 'KARNATAKA BANK'), (23, 'KOTAK MAHINDRA BANK'), (24, 'ORIENTAL BANK OF COMMERECE'), (25, 'PUNJAB NATIONAL BANK'), (26, 'PUNJAB & SIND BANK'), (27, 'STANDARD CHARTERED BANK'), (28, 'STATE BANK OF BIKANER AND JAIPUR'), (29, 'STATE BANK OF INDIA'), (30, 'STATE BANK OF HYDERABAD'), (31, 'STATE BANK OF TRAVANCORE'), (32, 'SOUTH INDIAN BANK'), (33, 'SYNDICATE BANK'), (34, 'TAMILNADU MERCANTILE BANK'), (35, 'TAMILNADU MERCANTILE BANK'), (36, 'UCO BANK'), (37, 'VIJAYA BANK'), (38, 'YES BANK')], default=0)),
                ('IFSC', models.CharField(default='', max_length=100)),
                ('accoutno', models.CharField(default='', max_length=100)),
                ('holdername', models.CharField(default='', max_length=255)),
                ('lastredem', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='redem',
            fields=[
                ('redemid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('redemamt', models.FloatField(default=0.0)),
                ('redemstatus', models.IntegerField(choices=[(0, 'Issued'), (1, 'Processing'), (2, 'Procced')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallets', models.ForeignKey(default='Wallet_1325', on_delete=django.db.models.deletion.CASCADE, to='users.wallet')),
            ],
        ),
    ]
