# Generated by Django 2.2.5 on 2020-08-26 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_redem_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='usersdetails',
            fields=[
                ('uid', models.CharField(auto_created=True, max_length=225, primary_key=True, serialize=False)),
                ('userimage', models.ImageField(default='default.jpg', upload_to='users')),
                ('country', models.CharField(blank=True, default='', max_length=255)),
                ('state', models.CharField(blank=True, default='', max_length=255)),
                ('address1', models.CharField(blank=True, default='', max_length=255)),
                ('adddres2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=255)),
                ('pincode', models.CharField(blank=True, default='', max_length=255)),
                ('phnumber1', models.CharField(blank=True, default='', max_length=255)),
                ('phnumber2', models.CharField(blank=True, default='', max_length=255)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='usersphone',
        ),
    ]
