# Generated by Django 2.2.5 on 2020-08-26 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200826_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='usersdetails',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.usersdetails'),
        ),
    ]
