# Generated by Django 2.2.5 on 2020-08-26 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_wallet_usersdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='usersdetails',
        ),
    ]
