# Generated by Django 2.2.5 on 2020-08-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200826_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redem',
            name='redemstatus',
            field=models.IntegerField(choices=[(1, 'Confirm'), (2, 'Pending'), (0, 'failed')], default=1),
        ),
    ]
