# Generated by Django 2.2.5 on 2020-08-27 19:10

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200826_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdetails',
            name='country',
            field=django_countries.fields.CountryField(default='IN', max_length=2),
        ),
    ]
