# Generated by Django 2.2.5 on 2020-08-29 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0019_auto_20200828_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='mymessages',
            fields=[
                ('messageid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('message', models.TextField(default='')),
                ('mdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('message_status', models.IntegerField(choices=[(1, 'seen'), (0, 'Not Seen')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
