# Generated by Django 2.2.5 on 2020-08-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_mymessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymessages',
            name='messageid',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
