# Generated by Django 2.2.5 on 2020-08-23 05:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        ('users', '0006_auto_20200820_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='tournaments',
            fields=[
                ('tourid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('tourname', models.CharField(blank=True, default='', max_length=100)),
                ('tourdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('noofplayer', models.IntegerField(default=100)),
                ('tournamenttype', models.IntegerField(choices=[(0, 'Single Player'), (1, 'Duo Players'), (2, '4 Players(Squad)')], default=0)),
                ('availseats', models.IntegerField(default=100)),
                ('occupiedseats', models.IntegerField(default=0)),
                ('entryfee', models.FloatField(default=100.0)),
                ('reward', models.FloatField(default=1000.0)),
                ('roomid', models.CharField(blank=True, default='', max_length=255)),
                ('roompassword', models.CharField(blank=True, default='', max_length=255)),
                ('tourstatus', models.IntegerField(choices=[(0, 'pending'), (1, 'Done'), (2, 'Canceled'), (3, 'started')], default=0)),
                ('game', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
            ],
        ),
        migrations.CreateModel(
            name='regestration',
            fields=[
                ('sid', models.CharField(default='solo', max_length=255, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'Done'), (2, 'Canceled'), (3, 'started')], default=0)),
                ('regestrationfee', models.FloatField(default=0.0)),
                ('razorpayorderid', models.CharField(blank=True, default='', max_length=255)),
                ('razorpaymentid', models.CharField(blank=True, default='', max_length=255)),
                ('razorpaysignature', models.CharField(blank=True, default='', max_length=255)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournaments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
