# Generated by Django 2.2.5 on 2020-08-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='winneremail',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
