# Generated by Django 2.2.5 on 2020-08-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournaments_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='regestration',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
