# Generated by Django 2.2.5 on 2020-08-16 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('gamename', models.CharField(blank=True, default='', max_length=255)),
                ('createdat', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
